# Generated by Django 4.0.4 on 2022-05-02 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0002_event_gametype_game_eventgamer_event_game_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='descriptions',
            new_name='description',
        ),
    ]
