# Generated by Django 4.0.4 on 2022-05-04 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0003_rename_descriptions_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(related_name='events', through='levelupapi.EventGamer', to='levelupapi.gamer'),
        ),
    ]
